### ISSUE TITLE
SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by SeoHyeokGyu** [SeoHyeokGyu/firstreactapp#1]
"C:\Program Files\nodejs\node.exe" C:\Users\Administrator\WebstormProjects\firstreactapp\src\App.js
file:///C:/Users/Administrator/WebstormProjects/firstreactapp/src/App.js:14
      <div>
      ^
SyntaxError: Unexpected token '<'
?[90m    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)?[39m
?[90m    at async link (internal/modules/esm/module_job.js:47:21)?[39m
Process finished with exit code 1

**Comment by SeoHyeokGyu** [comment]
일단 npm-start 했더니 오류가 나지 않음
